# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  fresh:
    desc: Fresh Build
    cmds:
      - clear
      - rm -rf build
      - cmake -B build -G Ninja -DLLVM_DIR=/usr/lib/llvm-22/lib/cmake/llvm
      - cmake --build build
      - ctest --test-dir build -L "unit"

  build:
    desc: Build
    cmds:
      - clear
      - cmake --build build

  test:
    desc: Test
    cmds:
      - clear
      - ctest --test-dir build -L "unit"

  build-test:
    desc: Build and Test
    cmds:
      - clear
      - cmake --build build
      - ctest --test-dir build -L "unit"

  tree:
    desc: Prints Tree Structure of libs
    cmds:
      - clear
      - tree libs -L 2

  run:
    desc: run main.wasp
    cmds:
      - clear
      - wasp run ./code/main.wasp
      - qbe ./code/build/main.ssa -o ./code/build/main.s
      - cc ./code/build/main.s -o ./code/build/main
      - ./code/build/main

  play:
    desc: Play with QBE
    cmds:
      - clear
      - qbe ./play/test.ssa -o ./play/test.s
      - cc ./play/test.s -o ./play/test
      - ./play/test
