name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build lld

    - name: Configure CMake
      run: cmake -B build -G Ninja

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build -L "unit" --output-on-failure

    - name: Run main
      run: |
        sudo ln -s $(pwd)/build/src/wasp /usr/local/bin/wasp
        wasp run ./code/main.wasp
